
import java.awt.*; 
import java.applet.*; 
// These classes are for Url's. 
import java.net.*;
import javax.swing.*;

public class ImageExampl extends JApplet implements ActionListener,MouseListener 
{ 
 // Your image name; 
     Image my_gif;
     JButton[] b = new JButton[5];
     
//Frame f=new Frame();
Panel p=new Panel();
 // The applet base URL 
     URL base;

 // This object will allow you to control loading 
     MediaTracker mt;

     public void ImageExampl()  
     {

  // initialize the MediaTracker 
          mt = new MediaTracker(this);
      
  // The try-catch is necassary when the URL isn't valid 
  // Ofcourse this one is valid, since it is generated by 
  // Java itself.

         try { 
   // getDocumentbase gets the applet path. 
               base = getDocumentBase(); 
         } 
         catch (Exception e) {}

  // Here we load the image. 
  // Only Gif and JPG are allowed. Transparant gif also. 
          my_gif = getImage(base,"1.gif");

  // tell the MediaTracker to kep an eye on this image, and give it ID 1; 
          mt.addImage(my_gif,1);

  // now tell the mediaTracker to stop the applet execution 
  // (in this example don't paint) until the images are fully loaded. 
  // must be in a try catch block.

         try { 
               mt.waitForAll(); 
          } 
          catch (InterruptedException  e) {}
ImageIcon i=new Image(my_gif);
    i.setbounds(20,20,80,80);
  // when the applet gets here then the images is loaded.
   p.add(i);
    f.add(p);
   f.setVisible(true);
  
     }

  public static void main(String args[])
{
   ImageExampl im=new ImageExampl();

}
}

// That's all. Images can alos be drawn without the mediaTracker but then 
// the screen will flicker. 
// a base URL variable is also not necessary but when you have lots of images to load 
// then it's shorter to type.

// Next is the basic GUI (Grphical User Interface) components. 
// go to guiExample.java

